import { StockItem, WarehouseTransaction } from '../../types';

export const demoStockItems: StockItem[] = [
  {
    id: 'demo-stock-001',
    sku: 'DA-CUP-250',
    item_name: 'Dallmayr Branded Cups 250ml',
    barcode: '600100250001',
    quantity: 3840,
    box_quantity: 80,
    pallet_quantity: 2,
    units_per_box: 48,
    notes: 'Core consumable for warehouse replenishment',
    image_url: '',
    is_active: true,
  },
  {
    id: 'demo-stock-002',
    sku: 'VM-FILTER-LG',
    item_name: 'Vending Machine Water Filter - Large',
    barcode: '600100250018',
    quantity: 42,
    box_quantity: 7,
    pallet_quantity: 0,
    units_per_box: 6,
    notes: 'Priority replenishment item for service technicians',
    image_url: '',
    is_active: true,
  },
  {
    id: 'demo-stock-003',
    sku: 'BEAN-CLASSIC-1KG',
    item_name: 'Dallmayr Classic Beans 1kg',
    barcode: '600100250025',
    quantity: 128,
    box_quantity: 16,
    pallet_quantity: 1,
    units_per_box: 8,
    notes: 'High-turnover coffee SKU',
    image_url: '',
    is_active: true,
  },
  {
    id: 'demo-stock-004',
    sku: 'VM-CLEAN-KIT',
    item_name: 'Machine Cleaning Kit',
    barcode: '600100250032',
    quantity: 8,
    box_quantity: 2,
    pallet_quantity: 0,
    units_per_box: 4,
    notes: 'Below reorder level for KZN routes',
    image_url: '',
    is_active: true,
  },
  {
    id: 'demo-stock-005',
    sku: 'NAYAX-MODEM',
    item_name: 'Nayax Telemetry Modem',
    barcode: '600100250049',
    quantity: 0,
    box_quantity: 0,
    pallet_quantity: 0,
    units_per_box: 1,
    notes: 'Out of stock, procurement action required',
    image_url: '',
    is_active: true,
  },
  {
    id: 'demo-stock-006',
    sku: 'SUGAR-STICK-1K',
    item_name: 'Sugar Sticks Bulk Pack',
    barcode: '600100250056',
    quantity: 960,
    box_quantity: 20,
    pallet_quantity: 1,
    units_per_box: 48,
    notes: 'Stable inventory',
    image_url: '',
    is_active: true,
  },
];

export const demoWarehouseTransactions: Array<WarehouseTransaction & { stock?: Pick<StockItem, 'item_name' | 'sku' | 'barcode'> }> = [
  {
    id: 'demo-tx-004',
    stock_id: 'demo-stock-002',
    user_id: 'demo-user',
    type: 'DISPATCH',
    quantity_change: -6,
    previous_quantity: 48,
    new_quantity: 42,
    reference_number: 'SCL-KZN-1048',
    notes: 'Issued to field technician route',
    created_at: new Date(Date.now() - 1000 * 60 * 38).toISOString(),
    stock: {
      item_name: 'Vending Machine Water Filter - Large',
      sku: 'VM-FILTER-LG',
      barcode: '600100250018',
    },
  },
  {
    id: 'demo-tx-003',
    stock_id: 'demo-stock-003',
    user_id: 'demo-user',
    type: 'RECEIVE',
    quantity_change: 64,
    previous_quantity: 64,
    new_quantity: 128,
    reference_number: 'PO-8841',
    notes: 'Goods received and counted',
    created_at: new Date(Date.now() - 1000 * 60 * 87).toISOString(),
    stock: {
      item_name: 'Dallmayr Classic Beans 1kg',
      sku: 'BEAN-CLASSIC-1KG',
      barcode: '600100250025',
    },
  },
  {
    id: 'demo-tx-002',
    stock_id: 'demo-stock-004',
    user_id: 'demo-user',
    type: 'DISPATCH',
    quantity_change: -4,
    previous_quantity: 12,
    new_quantity: 8,
    reference_number: 'WO-2197',
    notes: 'Cleaning kits dispatched to service bay',
    created_at: new Date(Date.now() - 1000 * 60 * 143).toISOString(),
    stock: {
      item_name: 'Machine Cleaning Kit',
      sku: 'VM-CLEAN-KIT',
      barcode: '600100250032',
    },
  },
  {
    id: 'demo-tx-001',
    stock_id: 'demo-stock-001',
    user_id: 'demo-user',
    type: 'RECEIVE',
    quantity_change: 960,
    previous_quantity: 2880,
    new_quantity: 3840,
    reference_number: 'PO-8832',
    notes: 'Palletized inbound stock',
    created_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    stock: {
      item_name: 'Dallmayr Branded Cups 250ml',
      sku: 'DA-CUP-250',
      barcode: '600100250001',
    },
  },
];
